name: Build Godot Project

on:
  push: {}
  pull_request: {}
  release:
    types:
      - created  

jobs:
  Godot:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux, windows, mac]
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: Build
        id: build
        uses: josephbmanley/build-godot-action@v1.4.1
        with:
          name: action-rpg
          preset: ${{ matrix.platform }}
          debugMode: "false"
      - name: Upload Artifact
        if: github.event.release.action == 'created'
        uses: actions/upload-artifact@v2
        with:
          name: Client - ${{ matrix.platform }}
          path: ${{ github.workspace }}/${{ steps.build.outputs.build }}